#Postgre SQL Config
spring.datasource.url=jdbc:postgresql://dpg-d7mf7ripmmbs73bvag40-a.singapore-postgres.render.com/moneymanager_suex
spring.datasource.username=moneymanager_suex_user
spring.datasource.password=PQnUGtErUyLxIMAZPC4RwGQanQ1eneSf